### ISSUE TITLE
Add information in docs regarding status/maturity/future?

### ISSUE THREAD

**Issue by einarpersson** [pola-rs/nodejs-polars#6]
Hi, This looks interesting

I wonder how feature complete this is (are things missing in node api compared to rust/python?), if it is production ready and how committed you are to supporting nodejs going forward (or if this was more of a "proof-of-concept") (reading [this](https://github.com/pola-rs/polars/issues/4148)) and the following

> "Releases happen quite often (weekly / every few days) at the moment, so updating polars regularly to get the latest bugfixes / features might not be a bad idea."

In the `README.md` there is a link to [node documentation](https://pola-rs.github.io/polars/nodejs-polars/html/index.html) which gives a 404. In the general [user guide](https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html) I see some references to javascript here and there, but examples are in rust/python.

I totally get that this is a new endeavour and things take time, I just want to assess if and / or when this might be ready for use and what I can except going forward.

I hope this question is OK, I think I am not the only one who has these questions in mind when discovering this repository for the first time. Maybe add a few answers to these types of questions in the readme?

**Comment by universalmind303** [comment]
Ideally we would like to have as much feature parity between the python & js bindings as possible. The main reason for moving js out of the pola-rs/polars was due to the fact that I am the only maintainer of the node bindings, while the main repo has many contributors. I try to do a release at least once a month to get the latest changes from upstream polars. 

If there are any other features that are available in py/rust, but not JS, please feel free to open up a new issue & ill see if it can be done.

**Comment by danielrhodes** [comment]
@universalmind303 I think the main issue I am seeing is that the main documentation doesn't include examples for nodejs. They are obviously pretty close so I can guess it, but it would be great to get that added.

**Comment by Bidek56** [comment]
@danielrhodes Is this still an issue? Thx
